### ISSUE TITLE
Add information about csv formatting

### ISSUE THREAD

**Issue by jflasher** [openaq/openaq-upload#15]
Just realized we probably need some way to let people know what format to upload the data in. We could always do this manually (by email) for now I suppose, but ultimately should prob live on page.

**Comment by nbumbarger** [comment]
Do you think it makes more sense to add CSV formatting instructions to the site itself, or should it live in the API documentation or as a readme in the repo? We discussed this at a scrum at one point, and our feeling at the time was that it should be incorporated into the docs.

**Comment by jflasher** [comment]
I guess it could live in the docs somewhere (and we just link to it from upload.openaq.org) but it's really only for the uploader, not useful information otherwise. The data format that they're uploading is really our internal format that we use to save things to the database, so not directly exposed to anyone via API or CSV downloads or anything.

**Comment by nbumbarger** [comment]
This was added in https://github.com/openaq/openaq-upload/pull/18. @danielfdsilva, I converted the the modal to use the modular design system template, and I can't figure out why the close button at the top-right doesn't work (it isn't a click target). Could you take a look when you review? The previous commit was written in HTML and seems to work fine.

**Comment by danielfdsilva** [comment]
@nbumbarger Problem with the modal was related to styling. 
The header would overlap the modal control. Fixed in https://github.com/openaq/openaq-upload/pull/18
