### ISSUE TITLE
Upload testing

### ISSUE THREAD

**Issue by nbumbarger** [openaq/openaq-upload#9]
@jflasher, would you mind adding a permissive CORS policy to the upload bucket, to help me finish testing? I spoke with @danielfdsilva and gathered that it shouldn't be much of a security problem in light of the signed URLs.

**Comment by jflasher** [comment]
Following policy is now on the bucket.

```
<CORSConfiguration>
    <CORSRule>
        <AllowedOrigin>*</AllowedOrigin>
        <AllowedMethod>PUT</AllowedMethod>
        <MaxAgeSeconds>3000</MaxAgeSeconds>
        <AllowedHeader>*</AllowedHeader>
    </CORSRule>
</CORSConfiguration>
```

**Comment by nbumbarger** [comment]
Thanks, @jflasher!
